import React from 'react';

export const Acadmics = (props) => {
  return <div>
      <h2>Acadmics</h2>
      <div>
      The B.Tech curriculum is designed keeping in mind the need to produce well-rounded graduates many of whom will go on to join industry in technical or managerial roles, or to join the administrative services as technocrats, while a few may aspire to research careers. Some may even go on to become entrepreneurs. Thus, at IIT Mandi, the students are exposed to a broad range of knowledge and skills that will enable them to perform well in tomorrow's increasingly complex and inter-dependent world. A B.Tech. student at IIT Mandi will study foundation courses in basic sciences, engineering sciences and practice, humanities and social sciences. In the chosen discipline, besides studying the core courses, the student will also study elective courses which will enable them to develop significant knowledge in a specialized area with exposure to research trends and developments. The category of free/open electives outside the chosen discipline will enable the student to obtain significant inter-disciplinary knowledge. The student can consult a 'Faculty Advisor' with regard to the planning of curriculum and other academic issues. <br /> In addition, the curriculum allows specialization in a 'Minor' area, by taking a set of 3-4 courses in another discipline. For example, a Mechanical engineering student can qualify for a minor in Computer Science or German language. <br /> The B. Tech. degree program allows a student to go on exchange visits of up to two semesters to other universities, both in India and abroad, for course work and projects. A number of B. Tech. students have already availed these opportunities to study at international institutions at European Union (EU). IIT Mandi's undergraduate students have visited IIT Madras and several EU institutions under academic exchange program including the TU9 Universities in Germany, Blekinge Institute of Technology in Sweden, Aalto University in Finland and IT University in Denmark. <br />Computer Science & Engineering trains students in programming, theoretical foundations, design of computer hardware and software, networks, artificial intelligence, databases, human-computer interfaces, etc. <br />Electrical Engineering at IIT Mandi includes communications, electronics, VLSI, electric power systems, and electrical machinery. Besides core courses covering all these areas, students will be able to specialize via elective courses.<br />

Mechanical Engineering covers materials, manufacturing processes, design of machinery, vehicles, etc.<br />

An important aspect of the curriculum is the integration of innovation and design into the learning process. This is achieved through a 'Design Practicum' model of learning, which is built into the curriculum. Thus, in the first year of the B.Tech program, the student carries out a 'reverse engineering' project, where student teams dismantle a common gadget/equipment, understand how it works and then put it back together in working order!<br />

At the second year level, students learn product design and development skills. Interdisciplinary teams of six students, randomly selected from different branches propose product ideas and then build working prototypes. Many of these product ideas are derived from the needs of the society. The products successfully built and demonstrated in the previous years include a fire-fighting robot, gesture-controlled 3-D hologram, automated ration vending machine etc.
<br />
At the third year level, the students have the option of working on an 'Interdisciplinary Socio-Technical Project' (ISTP). The ISTP exposes students to the complex interactions of technology and society. As part of ISTP, the students work in groups under the mentorship of a faculty member to identify and study the problems related to the society and try to suggest solutions for the same. Every year, a group of students from Worcester Polytechnic Institute (WPI), USA visits IIT Mandi and joins IIT Mandi students in carrying out the ISTP projects.
<br />
Finally, during the fourth year, the students have the option of doing a Major Technical Project (MTP) either individually or in a group. MTP is the capstone of the 4-year B. Tech programme. The project is expected to have a major technical contribution in the student's discipline and is intended to demonstrate a high degree of technical knowledge, innovativeness and maturity. The outcome of a B. Tech Project may be an innovative product or technology that addresses a problem of society, or it may be more theoretical or exploratory resulting in an advance in the frontiers of knowledge.
<br />
Overall, the curriculum at IIT Mandi is designed to encourage and enable the student to become well-qualified and well-rounded engineers in all respects.
      </div>
  </div>;
};
